/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_erick_martinez;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author usuario
 */
public class Principal extends javax.swing.JFrame {

    Administrar archivo = new Administrar("./ArchivoLab7.xxx");
    ArrayList<Organo> organos = new ArrayList();
    ArrayList<Paciente> pacientes = new ArrayList();
    ArrayList<Doctor> doctores = new ArrayList();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_color = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_nivelpotenciado = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_nivelprueba = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_organos = new javax.swing.JList<>();
        organo_e = new javax.swing.JRadioButton();
        organo_h = new javax.swing.JRadioButton();
        organo_ce = new javax.swing.JRadioButton();
        organo_pa = new javax.swing.JRadioButton();
        organo_co = new javax.swing.JRadioButton();
        organo_pu = new javax.swing.JRadioButton();
        organo_ri = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_altura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sexo_m = new javax.swing.JRadioButton();
        sexo_f = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        tf_sangre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_causa = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_pacientes = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_organos1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_edad1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_altura1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_peso1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        sexo_m1 = new javax.swing.JRadioButton();
        sexo_f1 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_horario = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_pacientes1 = new javax.swing.JList<>();
        tf_años = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        arbol_doctores = new javax.swing.JTree();
        dia_l = new javax.swing.JRadioButton();
        dia_ma = new javax.swing.JRadioButton();
        dia_v = new javax.swing.JRadioButton();
        dia_s = new javax.swing.JRadioButton();
        dia_mi = new javax.swing.JRadioButton();
        dia_d = new javax.swing.JRadioButton();
        dia_ju = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        grupo_sexo = new javax.swing.ButtonGroup();
        grupo_organo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jd_agregar.setPreferredSize(new java.awt.Dimension(845, 530));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Organos");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Color");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Nivel de Potenciado");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Nivel de Prueba");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Tipo de Organo");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Lista de Organos");

        jButton8.setText("Agregar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("Modificar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("Eliminar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jl_organos.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_organos);

        grupo_organo.add(organo_e);
        organo_e.setText("Estomago");

        grupo_organo.add(organo_h);
        organo_h.setText("Higado");

        grupo_organo.add(organo_ce);
        organo_ce.setText("Cerebreo");

        grupo_organo.add(organo_pa);
        organo_pa.setText("Pancreas");

        grupo_organo.add(organo_co);
        organo_co.setText("Corazon");

        grupo_organo.add(organo_pu);
        organo_pu.setText("Pulmones");

        grupo_organo.add(organo_ri);
        organo_ri.setText("Riñones");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nivelpotenciado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nivelprueba, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(organo_h)
                                    .addComponent(organo_e)
                                    .addComponent(organo_ce)
                                    .addComponent(organo_pa)
                                    .addComponent(organo_co)
                                    .addComponent(organo_pu)
                                    .addComponent(organo_ri))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel34)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10)
                                .addGap(321, 321, 321))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_nivelpotenciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nivelprueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton8)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(organo_e))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(organo_h)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organo_ce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organo_pa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(organo_co)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organo_pu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organo_ri)))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Organos", jPanel3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pacientes");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Altura");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Peso");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Sexo");

        grupo_sexo.add(sexo_m);
        sexo_m.setText("M");

        grupo_sexo.add(sexo_f);
        sexo_f.setText("F");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Fecha de Alta");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Tipo de Sangre");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Causa Visita");

        ta_causa.setColumns(20);
        ta_causa.setRows(5);
        jScrollPane1.setViewportView(ta_causa);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Lista de Organos");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Lista de Pacientes");

        jl_pacientes.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_pacientes);

        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jl_organos1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_organos1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sexo_m)
                                                .addGap(18, 18, 18)
                                                .addComponent(sexo_f))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tf_sangre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(30, 30, 30)
                                .addComponent(jButton3)
                                .addGap(28, 28, 28)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(139, 139, 139))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sexo_m)
                                            .addComponent(sexo_f))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addGap(32, 32, 32)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButton3)
                                .addComponent(jButton4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(49, 49, 49)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pacientes", jPanel1);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Doctores");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nombre");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Edad");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("ID");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Altura");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Peso");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Sexo");

        grupo_sexo.add(sexo_m1);
        sexo_m1.setText("M");

        grupo_sexo.add(sexo_f1);
        sexo_f1.setText("F");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Años de Doctor");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Horario");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Lista de Pacientes");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Lista de Doctores");

        jButton5.setText("Agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Modificar");

        jButton7.setText("Eliminar");

        jl_pacientes1.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_pacientes1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Doctores");
        arbol_doctores.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(arbol_doctores);

        dia_l.setText("Lunes");

        dia_ma.setText("Martes");

        dia_v.setText("Viernes");

        dia_s.setText("Sabado");

        dia_mi.setText("Miercoles");

        dia_d.setText("Domingo");

        dia_ju.setText("Jueves");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Dias de Trabajo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dia_v)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dia_s)
                        .addGap(18, 18, 18)
                        .addComponent(dia_d)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel17))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel18)
                                                        .addComponent(jLabel19))
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel20)
                                                        .addGap(6, 6, 6)))
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_altura1)
                                                    .addComponent(tf_peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(sexo_m1)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(sexo_f1))))))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_años, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(dia_l)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dia_ma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dia_mi)
                            .addGap(18, 18, 18)
                            .addComponent(dia_ju)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(94, 94, 94)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(tf_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tf_peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(sexo_m1)
                                            .addComponent(sexo_f1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(tf_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7)
                                    .addComponent(jButton5))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dia_l)
                            .addComponent(dia_ma)
                            .addComponent(dia_mi)
                            .addComponent(dia_ju))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia_v)
                    .addComponent(dia_s)
                    .addComponent(dia_d))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doctores", jPanel2);

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(845, 530));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Farmacia El Buen Tamal");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Agregar, Modificar Eliminar y Listar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("Reportes");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_agregar.setModal(true);
        jd_agregar.pack();
        jd_agregar.setLocationRelativeTo(this);
        jd_agregar.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        DefaultListModel m = (DefaultListModel) jl_organos.getModel();
        archivo.cargarArchivo();
        try {
            String color = tf_color.getText();
            int nivel_potenciado = Integer.parseInt(tf_nivelpotenciado.getText());
            int nivel_prueba = Integer.parseInt(tf_nivelprueba.getText());
            if (organo_e.isSelected()) {
                m.addElement(new Estomago(color, nivel_potenciado, nivel_prueba));
                archivo.setObject(new Estomago(color, nivel_potenciado, nivel_prueba));
                organos.add(new Estomago(color, nivel_potenciado, nivel_prueba));
            } else {
                if (organo_h.isSelected()) {
                    m.addElement(new Higado(color, nivel_potenciado, nivel_prueba));
                    archivo.setObject(new Higado(color, nivel_potenciado, nivel_prueba));
                    organos.add(new Higado(color, nivel_potenciado, nivel_prueba));
                } else {
                    if (organo_ce.isSelected()) {
                        m.addElement(new Cerebro(color, nivel_potenciado, nivel_prueba));
                        archivo.setObject(new Cerebro(color, nivel_potenciado, nivel_prueba));
                        organos.add(new Cerebro(color, nivel_potenciado, nivel_prueba));
                    } else {
                        if (organo_pa.isSelected()) {
                            m.addElement(new Pancreas(color, nivel_potenciado, nivel_prueba));
                            archivo.setObject(new Pancreas(color, nivel_potenciado, nivel_prueba));
                            organos.add(new Pancreas(color, nivel_potenciado, nivel_prueba));
                        } else {
                            if (organo_co.isSelected()) {
                                m.addElement(new Corazon(color, nivel_potenciado, nivel_prueba));
                                archivo.setObject(new Corazon(color, nivel_potenciado, nivel_prueba));
                                organos.add(new Corazon(color, nivel_potenciado, nivel_prueba));
                            } else {
                                if (organo_pu.isSelected()) {
                                    m.addElement(new Pulmones(color, nivel_potenciado, nivel_prueba));
                                    archivo.setObject(new Pulmones(color, nivel_potenciado, nivel_prueba));
                                    organos.add(new Pulmones(color, nivel_potenciado, nivel_prueba));
                                } else {
                                    if (organo_ri.isSelected()) {
                                        m.addElement(new Riñones(color, nivel_potenciado, nivel_prueba));
                                        archivo.setObject(new Riñones(color, nivel_potenciado, nivel_prueba));
                                        organos.add(new Riñones(color, nivel_potenciado, nivel_prueba));
                                    } else {
                                        JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun tipo!");
                                    }
                                }
                            }
                        }
                    }
                }
            }
            String resp = JOptionPane.showInputDialog(this, "Desea agregar caracteristicas? [s/n]");
            if (resp.equalsIgnoreCase("s")) {
                String resp2;
                do {
                    ((Organo) m.get(m.size() - 1)).getCaracteristicas().add(JOptionPane.showInputDialog(this, "Ingrese caracteristica:"));
                    resp2 = JOptionPane.showInputDialog(this, "Desea agregar otra caracteristicas? [s/n]");
                } while (resp2.equalsIgnoreCase("s"));
            }
            jl_organos.setModel(m);
            jl_organos1.setModel(m);
            archivo.escribirArchivo();
            tf_color.setText("");
            tf_nivelpotenciado.setText("");
            tf_nivelprueba.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos Incorrectos!");
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        DefaultListModel m = (DefaultListModel) jl_organos.getModel();
        if (jl_organos.getSelectedIndex() >= 0) {
            archivo.cargarArchivo();
            try {
                String color = tf_color.getText();
                int nivel_potenciado = Integer.parseInt(tf_nivelpotenciado.getText());
                int nivel_prueba = Integer.parseInt(tf_nivelprueba.getText());
                if (organo_e.isSelected()) {
                    m.addElement(new Estomago(color, nivel_potenciado, nivel_prueba));
                    archivo.setObject(new Estomago(color, nivel_potenciado, nivel_prueba));
                    organos.add(new Estomago(color, nivel_potenciado, nivel_prueba));
                } else {
                    if (organo_h.isSelected()) {
                        m.addElement(new Higado(color, nivel_potenciado, nivel_prueba));
                        archivo.setObject(new Higado(color, nivel_potenciado, nivel_prueba));
                        organos.add(new Higado(color, nivel_potenciado, nivel_prueba));
                    } else {
                        if (organo_ce.isSelected()) {
                            m.addElement(new Cerebro(color, nivel_potenciado, nivel_prueba));
                            archivo.setObject(new Cerebro(color, nivel_potenciado, nivel_prueba));
                            organos.add(new Cerebro(color, nivel_potenciado, nivel_prueba));
                        } else {
                            if (organo_pa.isSelected()) {
                                m.addElement(new Pancreas(color, nivel_potenciado, nivel_prueba));
                                archivo.setObject(new Pancreas(color, nivel_potenciado, nivel_prueba));
                                organos.add(new Pancreas(color, nivel_potenciado, nivel_prueba));
                            } else {
                                if (organo_co.isSelected()) {
                                    m.addElement(new Corazon(color, nivel_potenciado, nivel_prueba));
                                    archivo.setObject(new Corazon(color, nivel_potenciado, nivel_prueba));
                                    organos.add(new Corazon(color, nivel_potenciado, nivel_prueba));
                                } else {
                                    if (organo_pu.isSelected()) {
                                        m.addElement(new Pulmones(color, nivel_potenciado, nivel_prueba));
                                        archivo.setObject(new Pulmones(color, nivel_potenciado, nivel_prueba));
                                        organos.add(new Pulmones(color, nivel_potenciado, nivel_prueba));
                                    } else {
                                        if (organo_ri.isSelected()) {
                                            m.addElement(new Riñones(color, nivel_potenciado, nivel_prueba));
                                            archivo.setObject(new Riñones(color, nivel_potenciado, nivel_prueba));
                                            organos.add(new Riñones(color, nivel_potenciado, nivel_prueba));
                                        } else {
                                            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun tipo!");
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                organos.remove(jl_organos.getSelectedIndex());
                m.remove(jl_organos.getSelectedIndex());
                jl_organos.setModel(m);
                jl_organos1.setModel(m);
                archivo.escribirArchivo();
                tf_color.setText("");
                tf_nivelpotenciado.setText("");
                tf_nivelprueba.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No ha ingresado datos nuevos!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun organo!");
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        DefaultListModel m = (DefaultListModel) jl_organos.getModel();
        if (jl_organos.getSelectedIndex() >= 0) {
            archivo.cargarArchivo();
            organos.remove(jl_organos.getSelectedIndex());
            m.remove(jl_organos.getSelectedIndex());
            archivo.setObject(m);
            jl_organos.setModel(m);
            jl_organos1.setModel(m);
            archivo.escribirArchivo();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun organo!");
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultListModel m = (DefaultListModel) jl_pacientes.getModel();
        archivo.cargarArchivo();
        try {
            String nombre = tf_nombre.getText();
            int edad = Integer.parseInt(tf_edad.getText());
            int id = Integer.parseInt(tf_id.getText());
            double altura = Double.parseDouble(tf_altura.getText());
            double peso = Double.parseDouble(tf_peso.getText());
            String sexo = "";
            if (sexo_m.isSelected()) {
                sexo = "M";
            } else {
                if (sexo_f.isSelected()) {
                    sexo = "F";
                }
            }
            Date Fecha1 = new Date();
            Date Fecha2 = fecha.getDate();
            String sangre = tf_sangre.getText();
            String causa = ta_causa.getText();
            m.addElement(new Paciente(Fecha1, Fecha2, sangre, causa, nombre, edad, id, altura, peso, sexo));
            archivo.setObject(new Paciente(Fecha1, Fecha2, sangre, causa, nombre, edad, id, altura, peso, sexo));
            pacientes.add(new Paciente(Fecha1, Fecha2, sangre, causa, nombre, edad, id, altura, peso, sexo));
            String resp = JOptionPane.showInputDialog(this, "Desea agregar enfermedades? [s/n]");
            if (resp.equalsIgnoreCase("s")) {
                String resp2;
                do {
                    ((Paciente) m.get(m.size() - 1)).getEnfermedades().add(JOptionPane.showInputDialog(this, "Ingrese enfermedad:"));
                    resp2 = JOptionPane.showInputDialog(this, "Desea agregar otra enfermedad? [s/n]");
                } while (resp2.equalsIgnoreCase("s"));
            }
            String resp3 = JOptionPane.showInputDialog(this, "Desea agregar alergias? [s/n]");
            if (resp3.equalsIgnoreCase("s")) {
                String resp4;
                do {
                    ((Paciente) m.get(m.size() - 1)).getEnfermedades().add(JOptionPane.showInputDialog(this, "Ingrese alergia:"));
                    resp4 = JOptionPane.showInputDialog(this, "Desea agregar otra alergia? [s/n]");
                } while (resp4.equalsIgnoreCase("s"));
            }
            String resp5 = JOptionPane.showInputDialog(this, "Desea agregar organo? [s/n]");
            if (resp5.equalsIgnoreCase("s")) {
                String resp6;
                do {
                    ((Paciente) m.get(m.size() - 1)).getOrganos().add((organos.get(Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la posicion del organo:")))));
                    resp6 = JOptionPane.showInputDialog(this, "Desea agregar otro organo? [s/n]");
                } while (resp6.equalsIgnoreCase("s"));
            }
            jl_pacientes.setModel(m);
            jl_pacientes1.setModel(m);
            archivo.escribirArchivo();
            tf_nombre.setText("");
            tf_edad.setText("");
            tf_id.setText("");
            tf_altura.setText("");
            tf_peso.setText("");
            fecha.setDate(new Date());
            tf_sangre.setText("");
            ta_causa.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos Incorrectos!");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        DefaultListModel m = (DefaultListModel) jl_pacientes.getModel();
        if (jl_pacientes.getSelectedIndex() >= 0) {
            archivo.cargarArchivo();
            try {
                String nombre = tf_nombre.getText();
                int edad = Integer.parseInt(tf_edad.getText());
                int id = Integer.parseInt(tf_id.getText());
                double altura = Double.parseDouble(tf_altura.getText());
                double peso = Double.parseDouble(tf_peso.getText());
                String sexo = "";
                if (sexo_m.isSelected()) {
                    sexo = "M";
                } else {
                    if (sexo_f.isSelected()) {
                        sexo = "F";
                    }
                }
                Date Fecha1 = new Date();
                Date Fecha2 = fecha.getDate();
                String sangre = tf_sangre.getText();
                String causa = ta_causa.getText();
                m.addElement(new Paciente(Fecha1, Fecha2, sangre, causa, nombre, edad, id, altura, peso, sexo));
                archivo.setObject(new Paciente(Fecha1, Fecha2, sangre, causa, nombre, edad, id, altura, peso, sexo));
                pacientes.add(new Paciente(Fecha1, Fecha2, sangre, causa, nombre, edad, id, altura, peso, sexo));
                pacientes.remove(jl_pacientes.getSelectedIndex());
                m.remove(jl_pacientes.getSelectedIndex());
                jl_pacientes.setModel(m);
                jl_pacientes1.setModel(m);
                archivo.escribirArchivo();
                tf_nombre.setText("");
                tf_edad.setText("");
                tf_id.setText("");
                tf_altura.setText("");
                tf_peso.setText("");
                fecha.setDate(new Date());
                tf_sangre.setText("");
                ta_causa.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No ha ingresado datos nuevos!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun paciente!");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        DefaultListModel m = (DefaultListModel) jl_pacientes.getModel();
        if (jl_pacientes.getSelectedIndex() >= 0) {
            archivo.cargarArchivo();
            pacientes.remove(jl_pacientes.getSelectedIndex());
            m.remove(jl_pacientes.getSelectedIndex());
            archivo.setObject(m);
            jl_pacientes.setModel(m);
            jl_pacientes1.setModel(m);
            archivo.escribirArchivo();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun paciente!");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        DefaultTreeModel m = (DefaultTreeModel) arbol_doctores.getModel();
        try {
            ArrayList<String> dias = new ArrayList();
            ArrayList<String> especialidades = new ArrayList();
            String resp = JOptionPane.showInputDialog(this, "Desea agregar especialidades? [s/n]");
            if (resp.equalsIgnoreCase("s")) {
                String resp2;
                do {
                    especialidades.add(JOptionPane.showInputDialog(this, "Ingrese especialidad:"));
                    resp2 = JOptionPane.showInputDialog(this, "Desea agregar otra especialidad? [s/n]");
                } while (resp2.equalsIgnoreCase("s"));
            }
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nombre = new DefaultMutableTreeNode("Doctor " + tf_nombre1.getText());
            DefaultMutableTreeNode edad = new DefaultMutableTreeNode("Edad: " + tf_edad1.getText());
            DefaultMutableTreeNode id = new DefaultMutableTreeNode("ID: " + tf_id1.getText());
            DefaultMutableTreeNode altura = new DefaultMutableTreeNode("Altura: " + tf_altura1.getText());
            DefaultMutableTreeNode peso = new DefaultMutableTreeNode("Peso: " + tf_peso1.getText());
            DefaultMutableTreeNode sexo = null;
            String Sexo = "";
            if (sexo_m1.isSelected()) {
                sexo = new DefaultMutableTreeNode("Masculino");
                Sexo = "Masculino";
            } else {
                if (sexo_f1.isSelected()) {
                    sexo = new DefaultMutableTreeNode("Femenino");
                    Sexo = "Femenino";
                }
            }
            if (dia_l.isSelected()) {
                dias.add("Lunes");
            }
            if (dia_ma.isSelected()) {
                dias.add("Martes");
            }
            if (dia_mi.isSelected()) {
                dias.add("Miercoles");
            }
            if (dia_ju.isSelected()) {
                dias.add("Jueves");
            }
            if (dia_v.isSelected()) {
                dias.add("Viernes");
            }
            if (dia_s.isSelected()) {
                dias.add("Sabado");
            }
            if (dia_d.isSelected()) {
                dias.add("Domingo");
            }
            DefaultMutableTreeNode Pacientes = new DefaultMutableTreeNode("Pacientes");
            String resp3 = JOptionPane.showInputDialog(this, "Desea agregar paciente? [s/n]");
            if (resp3.equalsIgnoreCase("s")) {
                String resp4;
                do {
                    DefaultMutableTreeNode pac = new DefaultMutableTreeNode(((Persona) pacientes.get(Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la posicion del paciente:")))).getNombre());
                    Pacientes.add(pac);
                    resp4 = JOptionPane.showInputDialog(this, "Desea agregar otro paciente? [s/n]");
                } while (resp4.equalsIgnoreCase("s"));
            }
            DefaultMutableTreeNode dia = new DefaultMutableTreeNode(dias);
            DefaultMutableTreeNode especialidad = new DefaultMutableTreeNode(especialidades);
            DefaultMutableTreeNode años = new DefaultMutableTreeNode("Años: " + tf_años.getText());
            DefaultMutableTreeNode horario = new DefaultMutableTreeNode("Horario: " + tf_horario.getText());
            nombre.add(edad);
            nombre.add(id);
            nombre.add(altura);
            nombre.add(peso);
            nombre.add(sexo);
            nombre.add(años);
            nombre.add(horario);
            nombre.add(dia);
            nombre.add(especialidad);
            nombre.add(Pacientes);
            raiz.add(nombre);
            m.reload();
            doctores.add(new Doctor(Integer.parseInt(tf_años.getText()), tf_horario.getText(), tf_nombre1.getText(), Integer.parseInt(tf_edad1.getText()), Integer.parseInt(tf_id.getText()), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), Sexo));
            tf_años.setText("");
            tf_horario.setText("");
            tf_nombre1.setText("");
            tf_edad1.setText("");
            tf_id.setText("");
            tf_altura.setText("");
            tf_peso.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos Incorrectos!");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        int opcion = Integer.parseInt(JOptionPane.showInputDialog(this, "-> Reportes \n"
                + "1. Doctores \n"
                + "2. Pacientes \n"
                + "3. Organos \n"
                + "Ingrese el numero de su opcion:"));
        switch (opcion) {
            case 1:
                if (!doctores.isEmpty()) {
                    String doctor = "";
                    for (int i = 0; i < doctores.size(); i++) {
                        doctor += ((Doctor) doctores.get(i)).toString() + "\n";
                    }
                    JOptionPane.showMessageDialog(this, "Reporte Doctores: \n"
                            + doctor);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay doctores para crear el reporte!");
                }
                break;
            case 2:
                if (!pacientes.isEmpty()) {
                    String paciente = "";
                    for (int i = 0; i < pacientes.size(); i++) {
                        paciente += ((Paciente) pacientes.get(i)).toString() + "\n";
                    }
                    JOptionPane.showMessageDialog(this, "Reporte Pacientes: \n"
                            + paciente);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay pacientes para crear el reporte!");
                }
                break;
            case 3:
                if (!organos.isEmpty()) {
                    String organo = "";
                    for (int i = 0; i < organos.size(); i++) {
                        if (organos.get(i) instanceof Estomago) {
                            organo += "(Estomago)" + ((Organo) organos.get(i)).toString() + "\n";
                        } else {
                            if (organos.get(i) instanceof Higado) {
                                organo += "(Higado)" + ((Organo) organos.get(i)).toString() + "\n";
                            } else {
                                if (organos.get(i) instanceof Cerebro) {
                                    organo += "(Cerebro)" + ((Organo) organos.get(i)).toString() + "\n";
                                } else {
                                    if (organos.get(i) instanceof Pancreas) {
                                        organo += "(Pancreas)" + ((Organo) organos.get(i)).toString() + "\n";
                                    } else {
                                        if (organos.get(i) instanceof Pulmones) {
                                            organo += "(Pulmones)" + ((Organo) organos.get(i)).toString() + "\n";
                                        } else {
                                            if (organos.get(i) instanceof Riñones) {
                                                organo += "(Riñones)" + ((Organo) organos.get(i)).toString() + "\n";
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Reporte Organos: \n"
                            + organo);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay organos para crear el reporte!");
                }
                break;
        }
    }//GEN-LAST:event_jButton11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol_doctores;
    private javax.swing.JRadioButton dia_d;
    private javax.swing.JRadioButton dia_ju;
    private javax.swing.JRadioButton dia_l;
    private javax.swing.JRadioButton dia_ma;
    private javax.swing.JRadioButton dia_mi;
    private javax.swing.JRadioButton dia_s;
    private javax.swing.JRadioButton dia_v;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.ButtonGroup grupo_organo;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JList<String> jl_organos;
    private javax.swing.JList<String> jl_organos1;
    private javax.swing.JList<String> jl_pacientes;
    private javax.swing.JList<String> jl_pacientes1;
    private javax.swing.JRadioButton organo_ce;
    private javax.swing.JRadioButton organo_co;
    private javax.swing.JRadioButton organo_e;
    private javax.swing.JRadioButton organo_h;
    private javax.swing.JRadioButton organo_pa;
    private javax.swing.JRadioButton organo_pu;
    private javax.swing.JRadioButton organo_ri;
    private javax.swing.JRadioButton sexo_f;
    private javax.swing.JRadioButton sexo_f1;
    private javax.swing.JRadioButton sexo_m;
    private javax.swing.JRadioButton sexo_m1;
    private javax.swing.JTextArea ta_causa;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JTextField tf_altura1;
    private javax.swing.JTextField tf_años;
    private javax.swing.JTextField tf_color;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_horario;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_nivelpotenciado;
    private javax.swing.JTextField tf_nivelprueba;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_peso1;
    private javax.swing.JTextField tf_sangre;
    // End of variables declaration//GEN-END:variables

}
